/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application.views;

import application.dao.AlternativeDao;
import application.dao.CriteriaDao;
import application.daoimpl.AlternativeDaoImpl;
import application.daoimpl.CriteriaDaoImpl;
import application.models.AlternativeModel;
import application.models.AlternativeTableModel;
import application.models.CriteriaModel;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author mahasiswa unindra
 */
public class AlternativeView extends javax.swing.JPanel {

    private final AlternativeDao alternativeDao;
    private final CriteriaDao criteriaDao;
    private AddAlternativeDialog addAlternativeDialog = new AddAlternativeDialog(null, true);
    private String id;

    /**
     * Creates new form CandidateView
     */
    public AlternativeView() {
        initComponents();
        this.alternativeDao = new AlternativeDaoImpl();
        this.criteriaDao = new CriteriaDaoImpl();
        this.loadTable();
        buttonEdit.setBackground(Color.white);
        buttonAdd.setBackground(Color.white);
    }

    private void getDataTabel() {
        int selectedRow = tableCandidate.getSelectedRow();

        if (selectedRow >= 0) {
            // Get the actual AlternativeModel object from the table model
            AlternativeTableModel model = (AlternativeTableModel) tableCandidate.getModel();

            // Since AlternativeTableModel doesn't have a direct method to get the AlternativeModel,
            // we need to get it from the alternatives list
            // First, get the actual row index (considering sorting)
            int modelRow = tableCandidate.convertRowIndexToModel(selectedRow);

            // Get the AlternativeModel from the list
            List<AlternativeModel> alternatives = this.alternativeDao.findAll();
            AlternativeModel data = alternatives.get(modelRow);

            // Set the id for other operations
            this.id = String.valueOf(data.getId());

            // Pass the AlternativeModel object to the dialog
            addAlternativeDialog.setDataTabel(data);
        }
    }

    public void loadTable() {
        List<AlternativeModel> alternatives = this.alternativeDao.findAll();
        List<CriteriaModel> criterias = this.criteriaDao.findAll();
        if (criterias.isEmpty()) {
            criterias = List.of(
                    createCriteria("k1", "Kriteria 1"),
                    createCriteria("k2", "Kriteria 2"),
                    createCriteria("k3", "Kriteria 3"),
                    createCriteria("k4", "Kriteria 4")
            );
        }

        AlternativeTableModel alternativeTableModel = new AlternativeTableModel(alternatives, criterias);

        tableCandidate.setModel(alternativeTableModel);

        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tableCandidate.getModel());
        tableCandidate.setRowSorter(sorter);

        List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(1, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(3, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
    }

    private CriteriaModel createCriteria(String code, String name) {
        CriteriaModel c = new CriteriaModel();
        c.setCode(code);
        c.setName(name);
        return c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCandidate = new javax.swing.JTable();
        buttonAdd = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        note = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 247, 250));

        title.setBackground(new java.awt.Color(234, 244, 255));
        title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(0, 120, 218));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("  Data Alternatif Karyawan");
        title.setOpaque(true);

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        tableCandidate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.ID", "Nama", "Jenis Kelamin", "Posisi", "K1", "K2", "K3", "K4"
            }
        ));
        tableCandidate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCandidateMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCandidate);

        buttonAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonAdd.setForeground(new java.awt.Color(11, 91, 179));
        buttonAdd.setText("Tambah Data Alternatif");
        buttonAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 210, 226)));
        buttonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonAddMouseExited(evt);
            }
        });
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonEdit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonEdit.setForeground(new java.awt.Color(0, 120, 218));
        buttonEdit.setText("Ubah");
        buttonEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 210, 226)));
        buttonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonEditMouseExited(evt);
            }
        });
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(204, 0, 51));
        buttonDelete.setText("Hapus");
        buttonDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        buttonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonDeleteMouseExited(evt);
            }
        });
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        note.setText("Catatan : Edit/Hapus data alternatif, klik data pada tabel terlebih dahulu");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(560, Short.MAX_VALUE)
                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelLayout.createSequentialGroup()
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(note)
                                .addGroup(PanelLayout.createSequentialGroup()
                                    .addGap(439, 439, 439)
                                    .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(87, 87, 87)
                                    .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 48, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLayout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(note)
                    .addGap(18, 18, 18)
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buttonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addComponent(buttonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                    .addGap(0, 45, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(349, 349, 349))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableCandidateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCandidateMouseClicked
        // TODO add your handling code here
        getDataTabel();
    }//GEN-LAST:event_tableCandidateMouseClicked

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
        addAlternativeDialog.setTitleFrame("Tambah Data Alternatif Karyawan");
        addAlternativeDialog.clearForm();
        addAlternativeDialog.show();
        loadTable();
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here:
        if (id != null) {
            addAlternativeDialog.setTitleFrame("Ubah Data Alternatif Harga Karyawan");
            addAlternativeDialog.show();
            loadTable();
            id = null;
        } else {
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin diUbah! ");
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
        try {
            if (id != null) {
                int ok = JOptionPane.showConfirmDialog(null, "Hapus data alternatif?", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
                if (ok == 0) {
                    int deleted = alternativeDao.delete(Integer.parseInt(id));
                    if (deleted > 0) {
                        JOptionPane.showMessageDialog(null, "Data Berhasil dihapus ");
                        loadTable();
                        System.out.println(id);

                        id = null;
                        addAlternativeDialog.clearForm();
                    } else {
                        JOptionPane.showMessageDialog(this, "Gagal Menghapus Data");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus! ");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Menghapus Data");
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditMouseEntered
        // TODO add your handling code here:
        buttonEdit.setBackground(new Color(250, 239, 245));
    }//GEN-LAST:event_buttonEditMouseEntered

    private void buttonEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditMouseExited
        // TODO add your handling code here:
        buttonEdit.setBackground(Color.white);
    }//GEN-LAST:event_buttonEditMouseExited

    private void buttonDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDeleteMouseEntered
        // TODO add your handling code here:
        buttonDelete.setBackground(new Color(132, 0, 74));
    }//GEN-LAST:event_buttonDeleteMouseEntered

    private void buttonDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDeleteMouseExited
        // TODO add your handling code here:
        buttonDelete.setBackground(new Color(179, 30, 114));
    }//GEN-LAST:event_buttonDeleteMouseExited

    private void buttonAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseEntered
        // TODO add your handling code here:
        buttonAdd.setBackground(new Color(250, 239, 245));
    }//GEN-LAST:event_buttonAddMouseEntered

    private void buttonAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseExited
        // TODO add your handling code here:
        buttonAdd.setBackground(Color.white);
    }//GEN-LAST:event_buttonAddMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel note;
    private javax.swing.JTable tableCandidate;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
