/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application.views;

import application.dao.EvaluationDao;
import application.daoimpl.EvaluationDaoImpl;
import application.models.EvaluationModel;
import application.models.EvaluationTableModel;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author mahasiswa unindra
 */
public class EvaluationView extends javax.swing.JPanel {

    private final EvaluationDao evaluationDao;
    private int id;

    /**
     * Creates new form SelectionData
     */
    public EvaluationView() {
        initComponents();
        evaluationDao = new EvaluationDaoImpl();
        this.loadTable();
        tombolLihatPerhitunganAHP.setBackground(Color.white);
    }

    public void loadTable() {
        List<EvaluationModel> evaluations = this.evaluationDao.findAll();
        EvaluationTableModel evaluationTableModel = new EvaluationTableModel(evaluations);

        tableRanking.setModel(evaluationTableModel);

//        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tableRanking.getModel());
//        tableRanking.setRowSorter(sorter);
//
//        List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
//        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
//        sortKeys.add(new RowSorter.SortKey(1, SortOrder.ASCENDING));
//        sortKeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
//        sorter.setSortKeys(sortKeys);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRanking = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonDetail = new javax.swing.JButton();
        tombolLihatPerhitunganAHP = new javax.swing.JButton();
        buttonDelete1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 247, 250));

        judul.setBackground(new java.awt.Color(234, 244, 255));
        judul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        judul.setForeground(new java.awt.Color(0, 120, 218));
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("Penilaian Alternatif");
        judul.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tableRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ranking", "No.ID", "Nama Calon Pelamar", "No. HP", "Hasil Penilaian"
            }
        ));
        tableRanking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRankingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableRanking);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("- Untuk melihat ranking, pilih item pada tabel dan klik tombol \"Lihat detail\"");

        jLabel3.setText("Catatan : ");

        jLabel4.setText("- Hapus hasil penilaian dengan memilih item pada tabel dan klik tombol \"Hapus\" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(0, 53, Short.MAX_VALUE))
        );

        buttonDetail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonDetail.setForeground(new java.awt.Color(0, 120, 218));
        buttonDetail.setText("Lihat Detail");
        buttonDetail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        buttonDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonDetailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonDetailMouseExited(evt);
            }
        });
        buttonDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDetailActionPerformed(evt);
            }
        });

        tombolLihatPerhitunganAHP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tombolLihatPerhitunganAHP.setForeground(new java.awt.Color(11, 91, 179));
        tombolLihatPerhitunganAHP.setText("Mulai Penilaian Alternatif Metode AHP");
        tombolLihatPerhitunganAHP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 210, 226)));
        tombolLihatPerhitunganAHP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolLihatPerhitunganAHPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolLihatPerhitunganAHPMouseExited(evt);
            }
        });
        tombolLihatPerhitunganAHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolLihatPerhitunganAHPActionPerformed(evt);
            }
        });

        buttonDelete1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonDelete1.setForeground(new java.awt.Color(204, 0, 51));
        buttonDelete1.setText("Hapus");
        buttonDelete1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        buttonDelete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonDelete1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonDelete1MouseExited(evt);
            }
        });
        buttonDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDelete1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(buttonDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tombolLihatPerhitunganAHP, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tombolLihatPerhitunganAHP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(191, 191, 191))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableRankingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRankingMouseClicked
        try {
            int selectedRow = tableRanking.getSelectedRow();

            if (selectedRow >= 0) {
                TableModel model = tableRanking.getModel();
                Object idValue = model.getValueAt(selectedRow, 1);

                if (idValue != null) {
                    this.id = Integer.parseInt(idValue.toString());
                    System.out.println("Selected evaluation ID: " + this.id); // For debugging
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Format ID tidak valid.");
            this.id = 0;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error selecting row: " + e.getMessage());
            this.id = 0;
        }
    }//GEN-LAST:event_tableRankingMouseClicked

    private void buttonDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDetailActionPerformed
        int selectedRow = tableRanking.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data evaluasi terlebih dahulu.");
            return;
        }

        try {
            // Get evaluation ID and product name from the selected row
            TableModel model = tableRanking.getModel();
            Object idValue = model.getValueAt(selectedRow, 1); // Assuming ID is in column 0
            Object productNameValue = model.getValueAt(selectedRow, 3); // Assuming product name is in column 2, adjust as needed

            if (idValue == null) {
                JOptionPane.showMessageDialog(this, "Data evaluasi tidak valid.");
                return;
            }

            int evaluationId = Integer.parseInt(idValue.toString());
            String productName = productNameValue != null ? productNameValue.toString() : "Karyawan";

            // Create and configure the dialog
            ResultDetailDialog dialog = new ResultDetailDialog(null, true);
            dialog.setTitleFrame("Hasil Penilaian " + productName);
            dialog.setDataTabel(evaluationId);
            dialog.setVisible(true);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Format ID evaluasi tidak valid.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan detail hasil: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_buttonDetailActionPerformed

    private void tombolLihatPerhitunganAHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolLihatPerhitunganAHPActionPerformed
        // TODO add your handling code here:
        CalculationDialog dialog = new CalculationDialog(null, true);
        dialog.show();
//        new AHPCalculation().start();
        loadTable();
    }//GEN-LAST:event_tombolLihatPerhitunganAHPActionPerformed

    private void buttonDetailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDetailMouseEntered
        // TODO add your handling code here:
        buttonDetail.setBackground(new Color(132, 0, 74));
    }//GEN-LAST:event_buttonDetailMouseEntered

    private void buttonDetailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDetailMouseExited
        // TODO add your handling code here:
        buttonDetail.setBackground(new Color(179, 30, 114));
    }//GEN-LAST:event_buttonDetailMouseExited

    private void tombolLihatPerhitunganAHPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolLihatPerhitunganAHPMouseEntered
        // TODO add your handling code here:
        tombolLihatPerhitunganAHP.setBackground(new Color(250, 239, 245));
    }//GEN-LAST:event_tombolLihatPerhitunganAHPMouseEntered

    private void tombolLihatPerhitunganAHPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolLihatPerhitunganAHPMouseExited
        // TODO add your handling code here:
        tombolLihatPerhitunganAHP.setBackground(Color.white);
    }//GEN-LAST:event_tombolLihatPerhitunganAHPMouseExited

    private void buttonDelete1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDelete1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDelete1MouseEntered

    private void buttonDelete1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDelete1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDelete1MouseExited

    private void buttonDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelete1ActionPerformed
        // TODO add your handling code here:
        try {
            int ok = JOptionPane.showConfirmDialog(null, "Hapus Semua Data", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
            if (ok == 0) {
                evaluationDao.delete(this.id);
                JOptionPane.showMessageDialog(null, "Data Berhasil diHapus ");
                loadTable();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal diHapus " + e);
        }
    }//GEN-LAST:event_buttonDelete1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDelete1;
    private javax.swing.JButton buttonDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JTable tableRanking;
    private javax.swing.JButton tombolLihatPerhitunganAHP;
    // End of variables declaration//GEN-END:variables
}
