/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application.views;

import application.utils.DatabaseUtil;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author mahasiswa unindra
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuView
     */
    public MenuView() {

        initComponents();
        sliderMenuDefault();
        Pane.add(Home);
        Pane.repaint();
        Pane.revalidate();
    }

    private void sliderMenuDefault() {
        slideMenuLaporan.setVisible(false);
    }

    private void showSubMenu(JPanel subMenu) {
        if (subMenu.isVisible() == false) {
            subMenu.setVisible(true);
        } else {
            subMenu.setVisible(false);
        }
    }

    public void start() {
        JFrame frame = new MenuView();
        frame.setTitle("Menu Utama");

        UIManager.put("OptionPane.yesButtonText", "Ya");
        UIManager.put("OptionPane.noButtonText", "Tidak");

        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        frame.setLocationRelativeTo(null);
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                JFrame frame = (JFrame) e.getSource();

                int result = JOptionPane.showConfirmDialog(
                        frame,
                        "Apakah Anda yakin ingin keluar dari aplikasi?",
                        "Keluar dari Aplikasi",
                        JOptionPane.YES_NO_OPTION);

                if (result == JOptionPane.YES_OPTION) {
                    DatabaseUtil.getInstance().closeConnection();
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    System.exit(0);
                }
            }
        });
        // TODO add your custom frame code here:

        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        product = new javax.swing.JLabel();
        kriteria = new javax.swing.JLabel();
        slideMenuLaporan = new javax.swing.JPanel();
        laporan = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        seleksi = new javax.swing.JLabel();
        alternative = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        Pane = new javax.swing.JPanel();
        judul2 = new javax.swing.JLabel();

        Home.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selamat Datang, di Aplikasi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistem Pendukung Keputusan Pemilihan Karyawan Terbaik");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Menggunakan Metode AHP");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(501, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        Menu.setBackground(new java.awt.Color(0, 120, 218));
        Menu.setMaximumSize(new java.awt.Dimension(32767, 800));
        Menu.setPreferredSize(new java.awt.Dimension(183, 600));

        product.setBackground(new java.awt.Color(0, 120, 218));
        product.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        product.setForeground(new java.awt.Color(255, 255, 255));
        product.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        product.setText("Data Karyawan");
        product.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        product.setOpaque(true);
        product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productMouseExited(evt);
            }
        });

        kriteria.setBackground(new java.awt.Color(0, 120, 218));
        kriteria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kriteria.setForeground(new java.awt.Color(255, 255, 255));
        kriteria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kriteria.setText("Data Kriteria");
        kriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        kriteria.setOpaque(true);
        kriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kriteriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kriteriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kriteriaMouseExited(evt);
            }
        });

        slideMenuLaporan.setBackground(new java.awt.Color(0, 120, 218));
        slideMenuLaporan.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout slideMenuLaporanLayout = new javax.swing.GroupLayout(slideMenuLaporan);
        slideMenuLaporan.setLayout(slideMenuLaporanLayout);
        slideMenuLaporanLayout.setHorizontalGroup(
            slideMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        slideMenuLaporanLayout.setVerticalGroup(
            slideMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        laporan.setBackground(new java.awt.Color(0, 120, 218));
        laporan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        laporan.setForeground(new java.awt.Color(255, 255, 255));
        laporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laporan.setText("Laporan");
        laporan.setOpaque(true);
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanMouseExited(evt);
            }
        });

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logout.setText("Keluar");
        logout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logout.setOpaque(true);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        seleksi.setBackground(new java.awt.Color(0, 120, 218));
        seleksi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        seleksi.setForeground(new java.awt.Color(255, 255, 255));
        seleksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seleksi.setText("Seleksi");
        seleksi.setOpaque(true);
        seleksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seleksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seleksiMouseExited(evt);
            }
        });

        alternative.setBackground(new java.awt.Color(0, 120, 218));
        alternative.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alternative.setForeground(new java.awt.Color(255, 255, 255));
        alternative.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alternative.setText("Data Alternatif");
        alternative.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        alternative.setOpaque(true);
        alternative.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alternativeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alternativeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                alternativeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(product, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(slideMenuLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(seleksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(alternative, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(product, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slideMenuLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        judul1.setBackground(new java.awt.Color(0, 120, 218));
        judul1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        judul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/logo-company-200.png"))); // NOI18N
        judul1.setMaximumSize(new java.awt.Dimension(125, 125));
        judul1.setMinimumSize(new java.awt.Dimension(125, 125));
        judul1.setOpaque(true);
        judul1.setPreferredSize(new java.awt.Dimension(125, 125));

        Pane.setBackground(new java.awt.Color(250, 250, 250));
        Pane.setMaximumSize(new java.awt.Dimension(1200, 650));
        Pane.setMinimumSize(new java.awt.Dimension(380, 200));
        Pane.setPreferredSize(new java.awt.Dimension(600, 570));
        Pane.setLayout(new java.awt.CardLayout());

        judul2.setBackground(new java.awt.Color(213, 235, 255));
        judul2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        judul2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul2.setText("   SPK AHP PEMILIHAN KARYAWAN TERBAIK");
        judul2.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(judul1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judul2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(judul2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(judul1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pane, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productMouseClicked
        // TODO add your handling code here:
        // remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        // add Panel, add panel
        Pane.add(new KaryawanView());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_productMouseClicked

    private void productMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productMouseEntered
        // TODO add your handling code here:
//        product.setBackground(new Color(252, 186, 3));
        product.setCursor(new Cursor(Cursor.HAND_CURSOR));
        product.setForeground(new Color(10, 10, 10));
    }//GEN-LAST:event_productMouseEntered

    private void productMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productMouseExited
        // TODO add your handling code here:
//        product.setBackground(new Color(252, 186, 3));
        product.setForeground(Color.white);
    }//GEN-LAST:event_productMouseExited

    private void kriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kriteriaMouseClicked
        // TODO add your handling code here:
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        // add Panel, add panel
        Pane.add(new CriteriaData());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_kriteriaMouseClicked

    private void kriteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kriteriaMouseEntered
        // TODO add your handling code here:
//        kriteria.setBackground(new Color(252, 186, 3));
        kriteria.setCursor(new Cursor(Cursor.HAND_CURSOR));
        kriteria.setForeground(new Color(10, 10, 10));
    }//GEN-LAST:event_kriteriaMouseEntered

    private void kriteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kriteriaMouseExited
        // TODO add your handling code here:
//        kriteria.setBackground(new Color(252, 186, 3));
        kriteria.setForeground(Color.white);
    }//GEN-LAST:event_kriteriaMouseExited

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        // add Panel, add panel
        Pane.add(new ReportView());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_laporanMouseClicked

    private void laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseEntered
        // TODO add your handling code here:
//        laporan.setBackground(new Color(252, 186, 3));
        laporan.setCursor(new Cursor(Cursor.HAND_CURSOR));
        laporan.setForeground(new Color(10, 10, 10));
    }//GEN-LAST:event_laporanMouseEntered

    private void laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseExited
        // TODO add your handling code here:
//        laporan.setBackground(new Color(252, 186, 3));
        laporan.setForeground(Color.white);
    }//GEN-LAST:event_laporanMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new LoginView().start();
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setBackground(new Color(51, 51, 51));
        logout.setCursor(new Cursor(Cursor.HAND_CURSOR));
        logout.setForeground(new Color(255, 187, 0));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setBackground(Color.BLACK);
        logout.setForeground(Color.white);
    }//GEN-LAST:event_logoutMouseExited

    private void seleksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleksiMouseClicked
        // TODO add your handling code here:
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        //add Panel, add panel
        Pane.add(new EvaluationView());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_seleksiMouseClicked

    private void seleksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleksiMouseEntered
        // TODO add your handling code here:
//        seleksi.setBackground(new Color(252, 186, 3));
        seleksi.setCursor(new Cursor(Cursor.HAND_CURSOR));
        seleksi.setForeground(new Color(10, 10, 10));
    }//GEN-LAST:event_seleksiMouseEntered

    private void seleksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleksiMouseExited
        // TODO add your handling code here:
//        seleksi.setBackground(new Color(252, 186, 3));
        seleksi.setForeground(Color.white);
    }//GEN-LAST:event_seleksiMouseExited

    private void alternativeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alternativeMouseClicked
        // remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        // add Panel, add panel
        Pane.add(new AlternativeView());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_alternativeMouseClicked

    private void alternativeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alternativeMouseEntered
//        alternative.setBackground(new Color(252, 186, 3));
        alternative.setCursor(new Cursor(Cursor.HAND_CURSOR));
        alternative.setForeground(new Color(10, 10, 10));
    }//GEN-LAST:event_alternativeMouseEntered

    private void alternativeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alternativeMouseExited
//        alternative.setBackground(new Color(252, 186, 3));
        alternative.setForeground(Color.white);
    }//GEN-LAST:event_alternativeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Pane;
    private javax.swing.JLabel alternative;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel kriteria;
    private javax.swing.JLabel laporan;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel product;
    private javax.swing.JLabel seleksi;
    private javax.swing.JPanel slideMenuLaporan;
    // End of variables declaration//GEN-END:variables
}
