package application.views;

import application.dao.ResultDao;
import application.daoimpl.KaryawanDaoImpl;
import application.daoimpl.ResultDaoImpl;
import application.models.AlternativeModel;
import application.models.KaryawanModel;
import application.models.ResultModel;
import application.models.ResultTableModel;
import application.utils.DatabaseUtil;
import java.awt.Color;
import java.awt.Cursor;
import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.JRootPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import application.dao.KaryawanDao;

/**
 *
 * @author mahasiswa unindra
 */
public class ResultDetailDialog extends javax.swing.JDialog {

    private final ResultDao resultDao;
    private final KaryawanDao karyawanDao;
    Integer currentEvaluationId;

    /**
     * Creates new form DialogTambahData
     */
    public ResultDetailDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //add Panel, add panel(sebuah panel)
        Pane.add(PanelResult);
        Pane.repaint();
        Pane.revalidate();
        resultDao = new ResultDaoImpl();
        karyawanDao = new KaryawanDaoImpl();
        // Ensure proper sizing after all components are added
        pack();
        setLocationRelativeTo(parent);

        // Set minimum size to prevent it from being too small
        setMinimumSize(new java.awt.Dimension(888, 650));
    }

    public void setDataTabel(int evaluationId) {
        currentEvaluationId = evaluationId;
        List<ResultModel> results = resultDao.findByEvaluationId(evaluationId);
        ResultTableModel resultTableModel = new ResultTableModel(results);

        tableResult.setModel(resultTableModel);
    }

    public void setTitleFrame(String title) {
        judul.setText(title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelResult = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableResult = new javax.swing.JTable();
        buttonExport = new javax.swing.JLabel();
        IsiKosong = new javax.swing.JOptionPane();
        Pane = new javax.swing.JPanel();

        PanelResult.setBackground(new java.awt.Color(250, 250, 250));

        judul.setBackground(new java.awt.Color(213, 235, 255));
        judul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(0, 120, 218));
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("Hasil Penilaian");
        judul.setOpaque(true);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Ranking"));

        jLabel1.setText("Catatan:");

        jLabel2.setText("- Ranking diurutkan berdasarkan hasil penilaian terbesar sampai terkecil");

        tableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableResult);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 373, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        buttonExport.setBackground(new java.awt.Color(255, 255, 255));
        buttonExport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonExport.setForeground(new java.awt.Color(0, 120, 218));
        buttonExport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonExport.setText("Ekspor PDF");
        buttonExport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 210, 226)));
        buttonExport.setOpaque(true);
        buttonExport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonExportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonExportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonExportMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelResultLayout = new javax.swing.GroupLayout(PanelResult);
        PanelResult.setLayout(PanelResultLayout);
        PanelResultLayout.setHorizontalGroup(
            PanelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelResultLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonExport, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        PanelResultLayout.setVerticalGroup(
            PanelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResultLayout.createSequentialGroup()
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonExport, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Pane.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(888, 577));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonExportMouseClicked
        try {
            // Check if there are results to export
            if (currentEvaluationId == null) {
                JOptionPane.showMessageDialog(this, "Tidak ada data untuk diekspor.");
                return;
            }

            // Get results data
            List<ResultModel> results = resultDao.findByEvaluationId(currentEvaluationId);
            if (results.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tidak ada data hasil untuk diekspor.");
                return;
            }

            // Get product name from the first result
            String productName = "Karyawan Tidak Diketahui";
            if (!results.isEmpty() && results.get(0).getAlternative() != null
                    && results.get(0).getAlternative().getK() != null) {
                productName = results.get(0).getAlternative().getK().getNama();
            }

            String templateName = "LaporanRanking.jrxml";
            InputStream reportStream = getClass().getResourceAsStream("/resources/reports/" + templateName);

            if (reportStream == null) {
                JOptionPane.showMessageDialog(this, "Template laporan tidak ditemukan: " + templateName);
                return;
            }

            JasperDesign jd = JRXmlLoader.load(reportStream);

            Connection dbConnection = DatabaseUtil.getInstance().getConnection();
            JasperReport jr = JasperCompileManager.compileReport(jd);

            HashMap<String, Object> parameters = new HashMap<>();
            parameters.put("PATH", "resources/images/");
            parameters.put("PRODUCT_NAME", productName);
            parameters.put("EVALUATION_ID", currentEvaluationId);

            JasperPrint jp = JasperFillManager.fillReport(jr, parameters, dbConnection);

            // Use SwingUtilities to ensure proper threading
            final String finalProductName = productName;
            JasperViewer jasperViewer = new JasperViewer(jp, false);
            jasperViewer.setTitle("Laporan Ranking Penilaian Karyawan " + finalProductName);
            setModal(false);
            jasperViewer.setAlwaysOnTop(true);  //here
            jasperViewer.setVisible(true);
            setModal(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengekspor laporan: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_buttonExportMouseClicked

    private void buttonExportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonExportMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonExportMouseEntered

    private void buttonExportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonExportMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonExportMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ResultDetailDialog dialog = new ResultDetailDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane IsiKosong;
    private javax.swing.JPanel Pane;
    private javax.swing.JPanel PanelResult;
    private javax.swing.JLabel buttonExport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JTable tableResult;
    // End of variables declaration//GEN-END:variables

    void show(JRootPane rootPane) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
